name: "lint"
on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "!v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # action.yml
      - name: Check action.yml
        run: |
          scripts/lint-action.sh
        shell: bash

      # Workflow files
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
